### ISSUE TITLE
[BUG] Using the fork point to detect file changes.

### ISSUE THREAD

**Issue by grzegorzkrukowski** [tj-actions/changed-files#355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

We are experience a weird behaviour of changed files being returned on Pull Requests.

You can find my workflow runs here:
https://github.com/raycast/extensions/runs/5148147932?check_suite_focus=true#step:3:107
https://github.com/raycast/extensions/runs/5149182650?check_suite_focus=true#step:3:107

Both of them runs on the same PR and against same `main` - the only different is that on main there were 2 commits added meanwhile I was testing it, you can see it here:
<img width="822" alt="CleanShot 2022-02-11 at 00 28 42@2x" src="https://user-images.githubusercontent.com/1301068/153514269-d0605964-210c-4313-9ff5-f641f9eaad3e.png">

Goal of our PRs is to validate files added by PR - I want to get files that were modified in PRs - only those files.
But from time to time we are getting weird combination of files coming from changes done on `main` branch like you can see in first workflow run above.
Expected behaviour is to get just the list of changed files in given PR - so the correct one is the second run.

Our workflow is doing just this:
```
- name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
 - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v14.3
```

We have been playing with both:
```
base_sha: ${{ github.event.pull_request.base.sha }}
sha: ${{ github.event.pull_request.head.sha }}
```
and for some runs it helped, but it broke other PRs :/ it's a bit randomly behaving.

### To Reproduce

1. Use:
```
- name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
 - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v14.3
```

2. Create several PRs coming from forked repositories, meanwhile adding few commits in main repository
3. Observe how randomly sometimes commits from `main` are taken into account. Some commits on main can fix the problem or break it when you re-run existing checks on PRs.

### What OS are you seeing the problem on?

all

### Expected behavior?

I would expect consistency.

Goal is to always get just changed files in PR - ignoring any changes that happened on main.

### Relevant log output

Wrong:
https://github.com/raycast/extensions/runs/5148147932?check_suite_focus=true#step:3:107

Right:
https://github.com/raycast/extensions/runs/5149182650?check_suite_focus=true#step:3:107

Just re-runed after 2 commits were added.

### Anything else?

All repositories and workflows are public.
We have more runs like this happening:
https://github.com/raycast/extensions/runs/5143485235?check_suite_focus=true

Not sure if that's happening because of forking or what's the problem - if we are doing something wrong in our workflows, please advice.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by grzegorzkrukowski** [comment]
I am afraid that doesn't work:

Here is failing run for Forked PR - it doesn't see a commit.

https://github.com/raycast/extensions/actions/runs/1833497844

But thanks I will ask on `checkout` repository

**Comment by jackton1** [comment]
@grzegorzkrukowski After testing this I found the source of the error and should be resolved in #358

**Comment by grzegorzkrukowski** [comment]
Thanks @jackton1 - so now should I use my original version or one with ‘ref’ ?

**Comment by jackton1** [comment]
@grzegorzkrukowski It should be available in the latest release [v14.6](https://github.com/tj-actions/changed-files/releases).

**Comment by grzegorzkrukowski** [comment]
Ok still - which version should be working now ? :) the one where I checkout merged commit or one with “ref” ?

**Comment by jackton1** [comment]
You need to upgrade the action which fixes usage of merge commits 

```yaml

 - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
 - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v14.6

```

**Comment by grzegorzkrukowski** [comment]
Hey @jackton1 - I'm afraid it's still now working as it should:

Here is a run using code from your last message:
https://github.com/raycast/extensions/runs/5185457484?check_suite_focus=true

And here is a run when I tried to run with `ref` and `repository` to get PR repo:
https://github.com/raycast/extensions/runs/5185420161?check_suite_focus=true

**Comment by jackton1** [comment]
@grzegorzkrukowski Just to confirm using https://github.com/ad-m/github-push-action/issues/20#issuecomment-543139381 also doesn't solve the issue for you ??

**Comment by jackton1** [comment]
Can you also pass the head_ref to the action

```
- name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}
   - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v14.6
      with:
         base_ref: ${{ github.head_ref }}
```

**Comment by jackton1** [comment]
@grzegorzkrukowski I stumble upon a possible solution that might work but I’ll need your help in replicating the issue. 

Based on: https://github.com/tj-actions/changed-files/issues/355#issue-1131247960

- I've already made a pull request from a fork #379 
- I've merged a couple of PR's into the main branch #381 #380 


But I'm unable to replicate more files showing up in the [diff](https://github.com/tj-actions/changed-files/runs/5213159587?check_suite_focus=true)

Possible resolution: 
- https://stackoverflow.com/a/29813554/4584672

**Comment by grzegorzkrukowski** [comment]
Hey @jackton1 thanks for looking into this - let me see if I can reproduce it with your example

**Comment by grzegorzkrukowski** [comment]
@jackton1 I see you have been doing a lot of merges from main into your branch:
<img width="1067" alt="CleanShot 2022-02-16 at 10 21 20@2x" src="https://user-images.githubusercontent.com/1301068/154233982-46253c73-f969-42f2-a3f9-892d5449334b.png">

When you look at our example - we don't really have merges - branch is never merged with main or rebased after its created.

**Comment by jackton1** [comment]
@grzegorzkrukowski This should be resolved using the `use_fork_point` input set to `true`.

See: https://github.com/tj-actions/changed-files/runs/5228672940?check_suite_focus=true

![Screen Shot 2022-02-17 at 2 58 12 AM](https://user-images.githubusercontent.com/17484350/154431152-7bc0abcb-de0c-4867-927e-62632decd464.png)

**Comment by jackton1** [comment]
@grzegorzkrukowski  If you haven't already don't forget to star this project to help us reach a wider audience. Thanks

**Comment by grzegorzkrukowski** [comment]
Will do !! Thanks for your support ! Its one of the best axtions out there, couldnt live without it.

**Comment by grzegorzkrukowski** [comment]
Hey @jackton1 I am afraid it doesn't work for some reason in our repository:
https://github.com/raycast/extensions/runs/6129212969?check_suite_focus=true

It says about `fetch-depth: 0` - but it's there and still it doesn't find properly the fork point :( 
We are still constantly struggling with a proper solution there...

**Comment by jackton1** [comment]
I’m guessing this is the link to the PR 
https://github.com/raycast/extensions/pull/1266

I’ll take a look at it this weekend.

Something that stands out is the previous sha is unset which seems odd.

This also occurs on a fork that is based on a different branch than main/master

**Comment by grzegorzkrukowski** [comment]
Thanks for looking into this so quickly!

Yes, exactly that's the related PR.

We haven't been using the `use_fork_point` - I wanted to test it out just today and it didn't work - so I cannot really confirm it was working fully before in our setup.

**Comment by grzegorzkrukowski** [comment]
Hey - any news on this one? I still couldn't figure out a proper way to make it work.

**Comment by jackton1** [comment]
@grzegorzkrukowski The bug has been fixed in the latest release [v20](https://github.com/tj-actions/changed-files/releases/tag/v20)

**Comment by grzegorzkrukowski** [comment]
I am afraid I still cannot make it work...

Here is the log from a failed job for one of my tries when using it:
https://github.com/raycast/extensions/actions/runs/2420559225/attempts/2

It says:
```
Warning: Unable to locate the previous sha: 
```

and I am fetching with fetch-depth: 0 :(
