### ISSUE TITLE
[BUG] any_changed reports true without matching changed files

### ISSUE THREAD

**Issue by renedekat** [tj-actions/changed-files#67]
**Describe the bug**
When testing for changes in specific file types the any_changed output is true while it should be false.

**To Reproduce**
1. Add the following to a yml file
```     
- name: Get specific changed files
   id: specific_changed_files
   uses: tj-actions/changed-files@v6
   with:
      files: |
        .(php|css|js|vue)$
- name: Run step if any of the listed files above change
   if: steps.specific_changed_files.outputs.any_changed == 'true'
   run: |
      echo "One or more files listed above has changed."
```

2. Commit to GitHub without changing any of the match file types.

**Expected behavior**
`echo "One or more files listed above has changed."` should not run since no files are changed as can be seen in the screenshot. 

**Screenshots**
<img width="404" alt="Screenshot 2021-05-16 at 18 43 25" src="https://user-images.githubusercontent.com/8975204/118407086-f2c00a00-b676-11eb-9962-e5392735f46b.png">

**Comment by jackton1** [comment]
Thanks for catching this @renedekat, should be resolved here #68

**Comment by renedekat** [comment]
Hello @jackton1, the issue still gives the same result with version 6.1

**Comment by jackton1** [comment]
@renedekat This should now be resolved in `v6.2`

<img width="404" alt="Screen Shot 2021-05-17 at 4 34 00 AM" src="https://user-images.githubusercontent.com/17484350/118458836-2035a380-b6c9-11eb-82fe-711c6413ea3b.png">

Thanks

**Comment by renedekat** [comment]
@jackton1 , thanks, I will test it later today. Many thanks for the quick responses.
