### ISSUE TITLE
[BUG] changed-files v34.4.2 unable to locate a common ancestor

### ISSUE THREAD

**Issue by bduffany** [tj-actions/changed-files#809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

In the latest version, changed-files takes a very long time and seems to be running in a loop, fetching tons of commits. It then fails with "unable to locate a common ancestor."

### To Reproduce

Using checkout v3 like this:

```
      - name: Checkout
        uses: actions/checkout@v3
```

Using changed-files like this:

```
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34.4.2
```

I am seeing this on every PR.

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

Cloning the git repo should be relatively quick, not 5 minutes. And it shouldn't fail.

### Relevant log output

https://github.com/buildbuddy-io/buildbuddy/actions/runs/3481323441/jobs/5822266035

<details>
<summary>Output</summary>

From https://github.com/buildbuddy-io/buildbuddy
   * [new branch]      master     -> origin/master
  branch 'master' set up to track 'origin/master'.
  fatal: e9d7b108f57290b926d349d4f0e528cc596e29bd...c8a8c64fb48773d90ab42583ba288ad89a52df50: no merge base
  Fetching 40 commits...
  From https://github.com/buildbuddy-io/buildbuddy
   * branch            master     -> FETCH_HEAD
   * branch            c8a8c64fb48773d90ab42583ba288ad89a52df50 -> FETCH_HEAD
  fatal: e9d7b108f57290b926d349d4f0e528cc596e29bd...c8a8c64fb48773d90ab42583ba288ad89a52df50: no merge base
  Fetching 340 commits...
  From https://github.com/buildbuddy-io/buildbuddy
   * branch            master     -> FETCH_HEAD
   * branch            c8a8c64fb48773d90ab42583ba288ad89a52df50 -> FETCH_HEAD
  fatal: e9d7b108f57290b926d349d4f0e528cc596e29bd...c8a8c64fb48773d90ab42583ba288ad89a52df50: no merge base
  Fetching 640 commits...
  From https://github.com/buildbuddy-io/buildbuddy
   * branch              master     -> FETCH_HEAD
   * branch              c8a8c64fb48773d90ab42583ba288ad89a52df50 -> FETCH_HEAD
  fatal: e9d7b108f57290b926d349d4f0e528cc596e29bd...c8a8c64fb48773d90ab42583ba288ad89a52df50: no merge base
  Fetching 940 commits...
  From https://github.com/buildbuddy-io/buildbuddy
   * branch              master     -> FETCH_HEAD
   * branch              c8a8c64fb48773d90ab42583ba288ad89a52df50 -> FETCH_HEAD
  fatal: e9d7b108f57290b926d349d4f0e528cc596e29bd...c8a8c64fb48773d90ab42583ba288ad89a52df50: no merge base
  Fetching 1240 commits...
  From https://github.com/buildbuddy-io/buildbuddy
   * branch                master     -> FETCH_HEAD
   * branch                c8a8c64fb48773d90ab42583ba288ad89a52df50 -> FETCH_HEAD
  fatal: e9d7b108f57290b926d349d4f0e528cc596e29bd...c8a8c64fb48773d90ab42583ba288ad89a52df50: no merge base
  Fetching 1540 commits...
  From https://github.com/buildbuddy-io/buildbuddy
   * branch                master     -> FETCH_HEAD
   * branch                c8a8c64fb48773d90ab42583ba288ad89a52df50 -> FETCH_HEAD
  fatal: e9d7b108f57290b926d349d4f0e528cc596e29bd...c8a8c64fb48773d90ab42583ba288ad89a52df50: no merge base
  Fetching 1840 commits...
  From https://github.com/buildbuddy-io/buildbuddy
   * branch                master     -> FETCH_HEAD
   * branch                c8a8c64fb48773d90ab42583ba288ad89a52df50 -> FETCH_HEAD
  fatal: e9d7b108f57290b926d349d4f0e528cc596e29bd...c8a8c64fb48773d90ab42583ba288ad89a52df50: no merge base
  Fetching 2140 commits...
  From https://github.com/buildbuddy-io/buildbuddy
   * branch                master     -> FETCH_HEAD
   * branch                c8a8c64fb48773d90ab42583ba288ad89a52df50 -> FETCH_HEAD
  fatal: e9d7b108f57290b926d349d4f0e528cc596e29bd...c8a8c64fb48773d90ab42583ba288ad89a52df50: no merge base
  Fetching 2440 commits...
  From https://github.com/buildbuddy-io/buildbuddy
   * branch                master     -> FETCH_HEAD
   * branch                c8a8c64fb48773d90ab42583ba288ad89a52df50 -> FETCH_HEAD
  fatal: e9d7b108f57290b926d349d4f0e528cc596e29bd...c8a8c64fb48773d90ab42583ba288ad89a52df50: no merge base
  Fetching 2740 commits...
  From https://github.com/buildbuddy-io/buildbuddy
   * branch                master     -> FETCH_HEAD
   * branch                c8a8c64fb48773d90ab42583ba288ad89a52df50 -> FETCH_HEAD
  fatal: e9d7b108f57290b926d349d4f0e528cc596e29bd...c8a8c64fb48773d90ab42583ba288ad89a52df50: no merge base
  Fetching 3040 commits...
  From https://github.com/buildbuddy-io/buildbuddy
   * branch                master     -> FETCH_HEAD
   * branch                c8a8c64fb48773d90ab42583ba288ad89a52df50 -> FETCH_HEAD
  fatal: e9d7b108f57290b926d349d4f0e528cc596e29bd...c8a8c64fb48773d90ab42583ba288ad89a52df50: no merge base
  Fetching 3340 commits...
  From https://github.com/buildbuddy-io/buildbuddy
   * branch                master     -> FETCH_HEAD
   * branch                c8a8c64fb48773d90ab42583ba288ad89a52df50 -> FETCH_HEAD
  fatal: e9d7b108f57290b926d349d4f0e528cc596e29bd...c8a8c64fb48773d90ab42583ba288ad89a52df50: no merge base
  Fetching 3640 commits...
  From https://github.com/buildbuddy-io/buildbuddy
   * branch                master     -> FETCH_HEAD
   * branch                c8a8c64fb48773d90ab42583ba288ad89a52df50 -> FETCH_HEAD
  fatal: e9d7b108f57290b926d349d4f0e528cc596e29bd...c8a8c64fb48773d90ab42583ba288ad89a52df50: no merge base
  Fetching 3940 commits...
  From https://github.com/buildbuddy-io/buildbuddy
   * branch                master     -> FETCH_HEAD
   * branch                c8a8c64fb48773d90ab42583ba288ad89a52df50 -> FETCH_HEAD
  fatal: e9d7b108f57290b926d349d4f0e528cc596e29bd...c8a8c64fb48773d90ab42583ba288ad89a52df50: no merge base
  Fetching 4240 commits...
  From https://github.com/buildbuddy-io/buildbuddy
   * branch                master     -> FETCH_HEAD
   * branch                c8a8c64fb48773d90ab42583ba288ad89a52df50 -> FETCH_HEAD
  fatal: e9d7b108f57290b926d349d4f0e528cc596e29bd...c8a8c64fb48773d90ab42583ba288ad89a52df50: no merge base
  Fetching 4540 commits...
  From https://github.com/buildbuddy-io/buildbuddy
   * branch                master     -> FETCH_HEAD
   * branch                c8a8c64fb48773d90ab42583ba288ad89a52df50 -> FETCH_HEAD
  fatal: e9d7b108f57290b926d349d4f0e528cc596e29bd...c8a8c64fb48773d90ab42583ba288ad89a52df50: no merge base
  Fetching [484](https://github.com/buildbuddy-io/buildbuddy/actions/runs/3481323441/jobs/5822266035#step:3:486)0 commits...
  From https://github.com/buildbuddy-io/buildbuddy
   * branch                master     -> FETCH_HEAD
   * branch                c8a8c64fb48773d90ab42583ba288ad89a52df50 -> FETCH_HEAD
  fatal: e9d7b108f57290b926d349d4f0e528cc596e29bd...c8a8c64fb48773d90ab42583ba288ad89a52df50: no merge base
  Fetching 5140 commits...
  From https://github.com/buildbuddy-io/buildbuddy
   * branch                master     -> FETCH_HEAD
   * branch                c8a8c64fb[487](https://github.com/buildbuddy-io/buildbuddy/actions/runs/3481323441/jobs/5822266035#step:3:489)73d90ab42583ba288ad89a52df50 -> FETCH_HEAD
  Error: Unable to locate a common ancestor between master and c8a8c64fb48773d90ab42583ba288ad89a52df50
  Error: Process completed with exit code 1.
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tsigouris007** [comment]
Similar behavior for me too.
Version 34.4.2
Wasting 10 minutes on a loop and then failing as seen:
![ksnip_20221117-130158](https://user-images.githubusercontent.com/10864434/202429535-b31bc6e1-0cfb-4e5d-a5a6-68452505fb3c.png)

**Comment by jackton1** [comment]
High-level description: This bug occurs when the fork point and the last commit of the base branch have changed, resulting in errors finding the merge-base as the checkout action merges the tip of the target branch to the PR branch. 

To prevent this error going forward a pre-check to determine the validity of merge-base would be used falling back to the last commit of the target branch where necessary.

**Comment by jackton1** [comment]
@bduffany This issue has now been resolved in the latest release. Sorry for the delay.

**Comment by VaidyaAkhil-Groww** [comment]
@jackton1 still facing the same issue on
version: [v34.5.3](https://github.com/tj-actions/changed-files/commit/74dc2e8a7877b725678a2195226bd470f10c481b) (latest)

### Which OS?
Reproducible on Mac runner


attaching relevant snippets and screenshots:
```
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  ref: ''

            - name: Identify changed files
              id: identify-changed-files
              uses: tj-actions/changed-files@v34
```

<img width="1165" alt="Screenshot 2022-12-12 at 8 32 19 PM" src="https://user-images.githubusercontent.com/113657479/207081046-bad9d95b-d79f-4fc3-b69f-c0f0ce514f9c.png">

<img width="1176" alt="Screenshot 2022-12-12 at 8 33 48 PM" src="https://user-images.githubusercontent.com/113657479/207081071-39321074-a76f-4de9-818c-f1d79ca01779.png">

**Comment by williamboman** [comment]
I'm also experiencing this issue sporadically. See:

1. [First workflow](https://github.com/mason-org/mason-registry/actions/runs/3687596968/jobs/6241379538) failed due to being unable to calculate changed files.
2. I `$ git commit --amend -C HEAD` and force-push (`9b0d7e4 -> b162bb1`)
4. [It's now able to calculate changed files](https://github.com/mason-org/mason-registry/actions/runs/3687617345/jobs/6241423949) (the workflow fails for other reasons in subsequent jobs)

**Comment by jackton1** [comment]
@andybalaam Can you re-run the workflow to verify that the issue has been resolved?

**Comment by andybalaam** [comment]
It has definitely **not** been resolved in v34.6.0 - the above output is running at that version.

**Comment by williamboman** [comment]
@andybalaam There should be a new `v34.6.1` version, released ~2 hours ago.

**Comment by williamboman** [comment]
@jackton1 It seems to still struggle, see for example https://github.com/mason-org/mason-registry/actions/runs/3699988065/jobs/6269202682. Re-running doesn't seem to fix it.
